# Conjure sponsorship configuration.
# Uncomment + fill in any platform you want to enable.

# github: [<username>]
# patreon: <username>
# open_collective: <name>
# ko_fi: <username>
# tidelift: <platform>/<package>
# community_bridge: <project-name>
# liberapay: <username>
# issuehunt: <username>
# otechie: <username>
# lfx_crowdfunding: <project-name>
# polar: <username>
# buy_me_a_coffee: <username>
# thanks_dev: u/<username>
